server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://awngpzrnbdetsr:aeb1384120ea26c0507d0d57696f65fde4b23d2d3343da180f71a62074e69529@ec2-23-23-128-222.compute-1.amazonaws.com:5432/daie1greugd9s3
    username: awngpzrnbdetsr
    password: aeb1384120ea26c0507d0d57696f65fde4b23d2d3343da180f71a62074e69529
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
  version: 2.0

